### ISSUE TITLE
Add delay between each stage generated.

### ISSUE THREAD

**Issue by VFlyer** [Speakingevil/tallordered-keys#1]
On TP, when consecutive solves go through, it's very likely that the stages will be lost. This forces players to risk a potential chance that they will get a key that they were unable to record.
"Forget Me Not, Forget Everything, and more notably Forget This have a little buffer for stages, so they don't come in all at once. So, if modules are solved simultaniously, they briefly display the stages one at a time until the displayed stage is the current stage." -Espik

**Comment by eXish** [comment]
Issue has been resolved in pull request #2.
